### ISSUE TITLE
Language documentation

### ISSUE THREAD

**Issue by DiogoJorge1401** [Garoze/Lunasm#1]
Pretende escrever uma documentação incialmente simples de como utilizar sua linguagem, propósitos, etc.

**Comment by Garoze** [comment]
> Pretende escrever uma documentação incialmente simples de como utilizar sua linguagem, propósitos, etc.

Sinceramente eu não sei, a ideia do Lunasm é só me ajudar a escrever programas de teste para o meu fantasy console, porque de outra forma eu teria que escrever em hex na mão que é chato, pode ser que no futuro eu documente a sintaxe do assembly e tal, mas o plano era só usar para ajudar no desenvolvimento e depois eu iria fazer uma linguagem de alto nivel para o console em si

**Comment by Garoze** [comment]
Como não é uma issue relacionada ao código, e a duvida acredito que já foi respondida, eu estou fechando a issue.
